// <auto-generated />
using System;
using DateApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DateApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201012084701_LikeEntityAdded")]
    partial class LikeEntityAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.8.20407.4");

            modelBuilder.Entity("DateApp.Domain.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Interests")
                        .HasColumnType("TEXT");

                    b.Property<string>("Introduction")
                        .HasColumnType("TEXT");

                    b.Property<string>("KnownAs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<string>("LookingFor")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            City = "Greenbush",
                            Country = "Martinique",
                            Created = new DateTime(2020, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1956, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "female",
                            Interests = "Sit sit incididunt proident velit.",
                            Introduction = "Sunt esse aliqua ullamco in incididunt consequat commodo. Nisi ad esse elit ipsum commodo fugiat est ad. Incididunt nostrud incididunt nostrud sit excepteur occaecat.\r\n",
                            KnownAs = "Lisa",
                            LastActive = new DateTime(2020, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Dolor anim cupidatat occaecat aliquip et Lorem ut elit fugiat. Mollit eu pariatur est sunt. Minim fugiat sit do dolore eu elit ex do id sunt. Qui fugiat nostrud occaecat nisi est dolor qui fugiat laborum cillum. Occaecat consequat ex mollit commodo ad irure cillum nulla velit ex pariatur veniam cupidatat. Officia veniam officia non deserunt mollit.\r\n",
                            PasswordHash = new byte[] { 241, 244, 79, 51, 183, 6, 46, 160, 99, 206, 166, 109, 184, 163, 146, 196, 217, 9, 65, 195, 85, 172, 21, 154, 13, 247, 86, 178, 177, 5, 153, 41, 150, 69, 124, 254, 143, 122, 187, 11, 178, 80, 151, 136, 35, 110, 232, 43, 27, 94, 161, 131, 223, 93, 115, 196, 183, 124, 110, 50, 95, 111, 230, 48 },
                            PasswordSalt = new byte[] { 94, 223, 56, 100, 161, 248, 184, 140, 175, 74, 6, 80, 199, 122, 142, 52, 24, 120, 201, 57, 208, 136, 246, 3, 150, 66, 135, 206, 243, 102, 194, 165, 157, 229, 96, 255, 10, 63, 82, 156, 2, 30, 91, 55, 94, 44, 29, 69, 201, 77, 29, 216, 65, 206, 67, 184, 156, 250, 249, 252, 220, 238, 85, 21, 79, 90, 147, 208, 19, 46, 192, 88, 183, 204, 217, 230, 48, 205, 138, 79, 39, 67, 248, 179, 151, 220, 180, 117, 89, 128, 144, 56, 53, 203, 140, 46, 75, 144, 157, 168, 24, 129, 125, 215, 104, 188, 199, 213, 112, 152, 200, 252, 217, 254, 0, 204, 76, 179, 199, 244, 104, 140, 154, 152, 209, 183, 169, 200 },
                            Username = "lisa"
                        },
                        new
                        {
                            Id = 13,
                            City = "Greenbush",
                            Country = "Martinique",
                            Created = new DateTime(2020, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1956, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            Interests = "Sit sit incididunt proident velit.",
                            Introduction = "Sunt esse aliqua ullamco in incididunt consequat commodo. Nisi ad esse elit ipsum commodo fugiat est ad. Incididunt nostrud incididunt nostrud sit excepteur occaecat.\r\n",
                            KnownAs = "martinoo",
                            LastActive = new DateTime(2020, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Dolor anim cupidatat occaecat aliquip et Lorem ut elit fugiat. Mollit eu pariatur est sunt. Minim fugiat sit do dolore eu elit ex do id sunt. Qui fugiat nostrud occaecat nisi est dolor qui fugiat laborum cillum. Occaecat consequat ex mollit commodo ad irure cillum nulla velit ex pariatur veniam cupidatat. Officia veniam officia non deserunt mollit.\r\n",
                            PasswordHash = new byte[] { 241, 244, 79, 51, 183, 6, 46, 160, 99, 206, 166, 109, 184, 163, 146, 196, 217, 9, 65, 195, 85, 172, 21, 154, 13, 247, 86, 178, 177, 5, 153, 41, 150, 69, 124, 254, 143, 122, 187, 11, 178, 80, 151, 136, 35, 110, 232, 43, 27, 94, 161, 131, 223, 93, 115, 196, 183, 124, 110, 50, 95, 111, 230, 48 },
                            PasswordSalt = new byte[] { 94, 223, 56, 100, 161, 248, 184, 140, 175, 74, 6, 80, 199, 122, 142, 52, 24, 120, 201, 57, 208, 136, 246, 3, 150, 66, 135, 206, 243, 102, 194, 165, 157, 229, 96, 255, 10, 63, 82, 156, 2, 30, 91, 55, 94, 44, 29, 69, 201, 77, 29, 216, 65, 206, 67, 184, 156, 250, 249, 252, 220, 238, 85, 21, 79, 90, 147, 208, 19, 46, 192, 88, 183, 204, 217, 230, 48, 205, 138, 79, 39, 67, 248, 179, 151, 220, 180, 117, 89, 128, 144, 56, 53, 203, 140, 46, 75, 144, 157, 168, 24, 129, 125, 215, 104, 188, 199, 213, 112, 152, 200, 252, 217, 254, 0, 204, 76, 179, 199, 244, 104, 140, 154, 152, 209, 183, 169, 200 },
                            Username = "martin"
                        },
                        new
                        {
                            Id = 14,
                            City = "Greenbush",
                            Country = "Martinique",
                            Created = new DateTime(2020, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1956, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "male",
                            Interests = "Sit sit incididunt proident velit.",
                            Introduction = "Sunt esse aliqua ullamco in incididunt consequat commodo. Nisi ad esse elit ipsum commodo fugiat est ad. Incididunt nostrud incididunt nostrud sit excepteur occaecat.\r\n",
                            KnownAs = "barteko",
                            LastActive = new DateTime(2020, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Dolor anim cupidatat occaecat aliquip et Lorem ut elit fugiat. Mollit eu pariatur est sunt. Minim fugiat sit do dolore eu elit ex do id sunt. Qui fugiat nostrud occaecat nisi est dolor qui fugiat laborum cillum. Occaecat consequat ex mollit commodo ad irure cillum nulla velit ex pariatur veniam cupidatat. Officia veniam officia non deserunt mollit.\r\n",
                            PasswordHash = new byte[] { 241, 244, 79, 51, 183, 6, 46, 160, 99, 206, 166, 109, 184, 163, 146, 196, 217, 9, 65, 195, 85, 172, 21, 154, 13, 247, 86, 178, 177, 5, 153, 41, 150, 69, 124, 254, 143, 122, 187, 11, 178, 80, 151, 136, 35, 110, 232, 43, 27, 94, 161, 131, 223, 93, 115, 196, 183, 124, 110, 50, 95, 111, 230, 48 },
                            PasswordSalt = new byte[] { 94, 223, 56, 100, 161, 248, 184, 140, 175, 74, 6, 80, 199, 122, 142, 52, 24, 120, 201, 57, 208, 136, 246, 3, 150, 66, 135, 206, 243, 102, 194, 165, 157, 229, 96, 255, 10, 63, 82, 156, 2, 30, 91, 55, 94, 44, 29, 69, 201, 77, 29, 216, 65, 206, 67, 184, 156, 250, 249, 252, 220, 238, 85, 21, 79, 90, 147, 208, 19, 46, 192, 88, 183, 204, 217, 230, 48, 205, 138, 79, 39, 67, 248, 179, 151, 220, 180, 117, 89, 128, 144, 56, 53, 203, 140, 46, 75, 144, 157, 168, 24, 129, 125, 215, 104, 188, 199, 213, 112, 152, 200, 252, 217, 254, 0, 204, 76, 179, 199, 244, 104, 140, 154, 152, 209, 183, 169, 200 },
                            Username = "bartek"
                        });
                });

            modelBuilder.Entity("DateApp.Domain.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            AppUserId = 12,
                            IsMain = true,
                            PublicId = "5",
                            Url = "https://randomuser.me/api/portraits/women/54.jpg"
                        },
                        new
                        {
                            Id = 13,
                            AppUserId = 13,
                            IsMain = true,
                            PublicId = "5",
                            Url = "https://randomuser.me/api/portraits/women/50.jpg"
                        },
                        new
                        {
                            Id = 14,
                            AppUserId = 14,
                            IsMain = true,
                            PublicId = "5",
                            Url = "https://randomuser.me/api/portraits/women/52.jpg"
                        });
                });

            modelBuilder.Entity("DateApp.Domain.Models.UserLike", b =>
                {
                    b.Property<int>("SourceUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikedUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SourceUserId", "LikedUserId");

                    b.HasIndex("LikedUserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("DateApp.Domain.Models.Photo", b =>
                {
                    b.HasOne("DateApp.Domain.Models.AppUser", "AppUser")
                        .WithMany("Photos")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DateApp.Domain.Models.UserLike", b =>
                {
                    b.HasOne("DateApp.Domain.Models.AppUser", "LikedUser")
                        .WithMany("LikedByUsers")
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DateApp.Domain.Models.AppUser", "SourceUser")
                        .WithMany("LikedUsers")
                        .HasForeignKey("SourceUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
